url: https://blackwood.io
name: Miles Blackwood Robinson
description: blackwood is an exploration of music, code, design, words; the thoughts and projects of Miles Blackwood, a developer, educator and artist living in Boston, MA
title: baze blackwood on the net

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
