url: https://blackwood.io
name: Miles Blackwood Robinson
description: an exploration of music, code, design, words
title: blackwood

include: [_redirects]
plugins:
  - jekyll-sitemap

picture:
  source: 'assets/img'
  output: 'assets/generated'

algolia:
  application_id: OYRT4AO3TM
  index_name: blackwood

defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true

collections:
  links:
    output: true
